// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WeaponTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ranged);
	// Melee
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Chainsaw);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DemolitionGear);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShockBat);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalSword);

	// Ranged
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalShotgun);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalRifle);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalBurstRifle);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalGatling);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalSMG);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalLauncher2);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalHomingLauncher4);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrystalHomingHighSpeed4);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Fireball);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HomingFireball);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(IceShotgun);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThunderStrike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Comet);
}

namespace ToolTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Axe);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PickAxe);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hammer);
}

namespace CustomLocomotionAction
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mounted);
}

namespace RobotParts
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Core);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Body);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arm);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Booster);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Leg);
}

namespace ArmTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BalanceHeavy);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MeleeLight);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RangedStandard);
}

namespace BodyTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BalanceLight);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HumidityStandard);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TemperatureStandard);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BalanceHeavy);
}

namespace BoosterTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cyclic);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HighPower);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LongRanged);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Recovery);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Standard);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sustained);
}

namespace CoreTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tier1);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tier2);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tier3);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tier4);
}

namespace LegTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Quadrupedal);
	
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuadrupedalLight);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(BipedalStandard);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReverseBipedalLight);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuadrupedalHeavy);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ReverseBipedalStandard);
}

namespace ItemTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tools);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Consumable);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HelperBot);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RobotParts);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon);
}

namespace RegionBossTypeTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Kamish);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LavaBrute);
}

namespace KamishSkillTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThunderRush);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(KneelDash);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThunderLeap);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(FlyingHammer);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RetrieveHammer);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RhythmStrike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyStrike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyLeftSwing);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyRightSwing);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightRightSwing);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightLeftSwing);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightSlam);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightUpper);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DashAndLeap);
	
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_ThunderRush);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_KneelDash);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_ThunderLeap);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_DashAndLeap);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_FlyingHammer);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_RetrieveHammer);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_RhythmStrike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_HeavyStrike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_HeavyLeftSwing);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(B_HeavyRightSwing);
}

namespace LavaBruteSkillTags
{
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThrowingStones);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EarthRumbling);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShoulderTackle);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LavaBreath);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CreateLava);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GroundSmash);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SmashTwice);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyPushLA);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavySlapHand);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavySmash);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightSpike);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightSwingLA);
	CR4S_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LightSwingRA);
}